#!/usr/bin/env ruby

if STDOUT.isatty
  $color = {
    normal: "",
    gray: "\e[30m",
    red: "\e[31m",
    green: "\e[32m",
    yellow: "\e[33m",
    blue: "\e[34m",
    magenta: "\e[35m",
    cyan: "\e[36m",
    white: "\e[37m",
    reset: "\e[m",
  }
else
  $color = {}
end

$color.merge!({
  current: $color[:green],
  remote: $color[:red],
  upstream: $color[:blue],
  worktree: $color[:cyan],
  local: $color[:normal],
})

def calc_max_width
  refs = []
  refs << 'refs/heads/' if ARGV.include?('-a') || !ARGV.include?('-r')
  refs << 'refs/remotes/' if ARGV.include?('-a') || ARGV.include?('-r')

  IO.popen(%w[git for-each-ref --format=%(refname:lstrip=2)] + refs) do |io|
    io.each(chomp: true).map do |line|
      line.length
    end.max
  end
end

$verbose = !!ARGV.delete('-v')
$track = !!ARGV.delete('-t')

$max_width = calc_max_width

local = '%%(if)%%(HEAD)%%(then)* %s%%(else)%%(if)%%(worktreepath)%%(then)+ %s%%(else)  %s%%(end)%%(end)' %
  [ $color[:current], $color[:worktree], $color[:local] ]
remote = '  %s' % [ $color[:remote] ]

local << '%%(align:%d,left)%%(refname:lstrip=2)%%(end)%s' % [ $max_width + 1, $color[:reset] ]
remote << '%%(align:%d,left)%%(refname:lstrip=2)%%(end)%s' % [ $max_width + 1, $color[:reset] ]

ss, se = $verbose ? [ '[', ']' ] : [ '', '' ]

track = $track ? '%(upstream:trackshort)' : ''
local << "%%(if)%%(upstream)%%(then)#{ss}%s%%(upstream:short)%s%s#{se} %%(end)" %
  [ $color[:upstream], $color [:reset], track ]

remote << "%%(if)%%(symref)%%(then)#{ss}%s%%(symref:short)%s#{se} %%(end)" %
  [ $color[:upstream], $color [:reset] ]

fmt = '%%(if:notequals=refs/remotes)%%(refname:rstrip=-2)%%(then)%s%%(else)%s%%(end)' % [ local, remote ]
fmt << '%(contents:subject)' if $verbose

system(*%W[git branch --list --sort=-committerdate --format=#{fmt}] + ARGV)
